### ISSUE TITLE
Websocket support

### ISSUE THREAD

**Issue by balazsbanyai** [j2objcgradle/gradle#1]
Hi, 

I'm curious to know whether you've had any luck with translating java websocket implementations to objc?

We've been trying hard for some time, but we couldn't get any java implementation working. We've tried okhttp (`j2objc "co.doppl.com.squareup.okhttp3:okhttp:3.4.2.6", j2objc "co.doppl.com.squareup.okhttp3:okhttp-ws:3.4.2.6"`) and `org.java-websocket:Java-WebSocket:1.3.8` but we are still looking for the proper solution. Do you have any experience or suggestions on how should we proceed?

**Comment by kpgalligan** [comment]
For the most part, the OKHttp dependencies exist for their interfaces to be used in Retrofit. OKHttp itself worked, but only for http. https connections aren't implemented because the underlying ssl components don't exist in J2objc. I haven't ever tried anything with websockets and J2objc.

On the longer term todo list is to trim the OKHttp dependencies and make it clear that you shouldn't use them directly.

**Comment by kpgalligan** [comment]
So, to be more clear. When we use connections in J2objc, we're never *really* using OKHttp. Retrofit uses some interfaces from OKHttp, which we implement with the URLSession stack from iOS. In a few places we create a connection directly, but use HttpURLConnection in Java, which also delegates to the iOS stack under the hood in J2objc.

**Comment by balazsbanyai** [comment]
Excellent, that cleared my vision, thank you very much!
